/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "MyAuth": {
      "type": "sst.aws.Auth"
      "url": string
    }
    "MyBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "MyNextjsSite": {
      "type": "sst.aws.Astro"
      "url": string
    }
    "MyRouter": {
      "type": "sst.aws.Router"
      "url": string
    }
    "MyRouterAnalogSite": {
      "type": "sst.aws.Analog"
    }
    "MyRouterApp": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "MyRouterAstroSite": {
      "type": "sst.aws.Astro"
    }
    "MyRouterNextSite": {
      "type": "sst.aws.Nextjs"
    }
    "MyRouterNuxtSite": {
      "type": "sst.aws.Nuxt"
    }
    "MyRouterRemixSite": {
      "type": "sst.aws.Remix"
    }
    "MyRouterSite": {
      "type": "sst.aws.React"
    }
    "MyRouterSolidSite": {
      "type": "sst.aws.SolidStart"
    }
    "MyRouterSvelteSite": {
      "type": "sst.aws.SvelteKit"
    }
    "MyRouterTanStackStartSite": {
      "type": "sst.aws.TanstackStart"
    }
    "MyStaticSite": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "MyVpc": {
      "type": "sst.aws.Vpc"
    }
    "Web": {
      "type": "sst.aws.StaticSite"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}