/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "GOOGLE_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_CLIENT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MyAuth": {
      "type": "sst.aws.Auth"
      "url": string
    }
    "MyBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "MyNextjsSite": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "MyRouter": {
      "type": "sst.aws.Router"
      "url": string
    }
    "MyRouterApp": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "MyRouterAstro": {
      "type": "sst.aws.Astro"
      "url": string
    }
    "MyStaticSite": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "MyVpc": {
      "type": "sst.aws.Vpc"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}