/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "MyApp": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "MyAstro4Site": {
      "type": "sst.aws.Astro"
      "url": string
    }
    "MyAstro5Site": {
      "type": "sst.aws.Astro"
      "url": string
    }
    "MyAuth": {
      "type": "sst.aws.Auth"
      "url": string
    }
    "MyBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "MyReactRouter7Site": {
      "type": "sst.aws.React"
      "url": string
    }
    "MyRouter": {
      "type": "sst.aws.Router"
      "url": string
    }
    "MyRouter2": {
      "type": "sst.aws.Router"
      "url": string
    }
    "MyTanstackSite": {
      "type": "sst.aws.TanstackStart"
      "url": string
    }
    "MyVpc": {
      "type": "sst.aws.Vpc"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}