[project]
name = "sst"
version = "0.2.0"
description = "SST SDK"
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["cryptography>=43.0.3"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
